---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: silverblue-surface

description: A custom Fedora Silverblue based distro using the linux-surface kernel for Microsoft Surface devices

base-image: ghcr.io/ublue-os/silverblue-main
image-version: "44"

modules:
  # Copy custom system files
  - type: files
    files:
      - source: system
        destination: /

  # Add Linux Surface repository
  - type: script
    snippets:
      - |
        curl -fsSL https://pkg.surfacelinux.com/fedora/linux-surface.repo \
          -o /etc/yum.repos.d/linux-surface.repo

        # Surface Linux has not published Fedora 44 packages yet.
        # Use Fedora 43 kernel packages instead.
        sed -i '/^baseurl=/ s/\$releasever/43/g' \
          /etc/yum.repos.d/linux-surface.repo

        rpm --import \
          https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc

  # Replace Fedora kernel and selected applications
  - type: dnf
    remove:
      packages:
        # Replace Firefox RPM with Flatpak
        - firefox
        - firefox-langpacks

        # Replace GNOME Software with Bazaar
        - gnome-software
        - gnome-software-rpm-ostree
        - gnome-software-flatpak
        - gnome-system-monitor

        # Remove Fedora kernel packages
        - kernel
        - kernel-core
        - kernel-modules
        - kernel-modules-core
        - kernel-modules-extra

    install:
      packages:
        # Linux Surface kernel
        - kernel-surface

        # Surface hardware support
        - iptsd
        - thermald

        # Secure Boot support
        - surface-secureboot

        # Flatpak support
        - flatpak

  # Wait for networking before services that need internet
  - type: systemd
    system:
      enabled:
        - NetworkManager-wait-online.service

  # Default applications
  - type: default-flatpaks
    configurations:
      - scope: system
        notify: false
        install:

          # Browser
          - org.mozilla.firefox

          # App store
          - io.github.kolunmi.Bazaar

          # Flatpak management
          - io.github.flattool.Warehouse
          - com.github.tchx84.Flatseal

          # GNOME extensions
          - com.mattjakeman.ExtensionManager

          # AppImage management
          - it.mijorus.gearlever

          # GNOME utilities
          - org.gnome.Evince
          - org.gnome.TextEditor
          - org.gnome.Loupe
          - org.gnome.FileRoller
          - org.gnome.Weather
          - org.gnome.Calendar
          - org.gnome.Contacts
          - org.gnome.clocks
          - org.gnome.Calculator
          - org.gnome.Maps
          - org.gnome.Snapshot
          - org.gnome.baobab
          - org.gnome.Characters
          - org.gnome.font-viewer
          - org.gnome.Logs
          - net.nokyan.Resources

      - scope: user

  # Sign image
  - type: signing
