---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: silverblue-surface

description: A custom Fedora Silverblue based distro using the linux-surface kernel for use on Microsoft Surface devices

base-image: quay.io/fedora-ostree-desktops/silverblue
image-version: "44"

modules:
  - type: files
    files:
      - source: system
        destination: /

  # Add Surface Linux repository
  - type: script
    snippets:
      - |
        curl -fsSL https://pkg.surfacelinux.com/fedora/linux-surface.repo \
          -o /etc/yum.repos.d/linux-surface.repo

        # Surface Linux has not yet published Fedora 44 packages
        sed -i '/^baseurl=/ s/\$releasever/43/g' \
          /etc/yum.repos.d/linux-surface.repo

        rpm --import \
          https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc

  - type: dnf
    remove:
      packages:
        # Remove Firefox RPMs
        - firefox
        - firefox-langpacks

        # Remove Fedora kernel packages
        - kernel
        - kernel-core
        - kernel-modules
        - kernel-modules-core
        - kernel-modules-extra

    install:
      packages:
        # Surface Linux kernel
        - kernel-surface

        # Surface touchscreen / pen support
        - iptsd

        # Optional Secure Boot support
        - surface-secureboot

  - type: default-flatpaks
    configurations:
      - scope: system
        notify: true
        install:
          - org.mozilla.firefox

      - scope: user

  - type: signing
